#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")/../src/server"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Update server project environment variables.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        pushd "${DIR}"

        if aws s3 cp "s3://${DB_SETTINGS_BUCKET}/.env" ".env"; then
            echo "Updated environment variables file from ${DB_SETTINGS_BUCKET}"
        elif [[ ! -f ".env" ]]; then
            cp .env.sample .env
            echo "Updated environment variables file from .env.sample"
        fi

        popd
    fi
fi