#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Start client application.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ./scripts/update
        yarn run start
    fi
fi
