#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Enter a database shell.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose \
            run --rm database bash -c "psql -U district_builder -d district_builder"
    fi
fi
