#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Load region configs and a test organization for development purposes.

This avoids having to process GeoJSON locally and publish it to S3.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Bring up PostgreSQL and NestJS in a way that respects
        # configured service health checks.
        docker-compose \
            -f docker-compose.yml \
            up -d database server

        # Different regions for testing different scenarios:
        #  - Dane County is a hidden / non-state region
        #  - PA has '16 but not '20 political data
        #  - IL has both '16 and '20 political data
        #  - DE appears twice, with an archived '10 census version and an unarchived '20 census version
        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              INSERT INTO region_config
              VALUES (
                '4a48268f-ddcf-4ae9-b41f-23cda93c3eba',
                'Dane County',
                'US',
                'WI',
                's3://global-districtbuilder-dev-us-east-1/regions/US/WI/2021-09-02T18:57:17.123Z/',
                DEFAULT,
                TRUE,
                DEFAULT,
                '2020'
              ),
              (
                '2d0af0fe-e43a-4ac5-a19b-b639734b9221',
                'San Bernadino',
                'US',
                'CA',
                's3://global-districtbuilder-dev-us-east-1/regions/US/CA/2021-09-30T18:00:31.844Z/',
                DEFAULT,
                TRUE,
                DEFAULT,
                '2020'
              ),
              (
                'e8f66491-4a6d-45a9-b606-7aabdf91fb76',
                'Wisconsin',
                'US',
                'WI',
                's3://global-districtbuilder-dev-us-east-1/regions/US/WI/2021-08-13T01:25:55.432Z/',
                DEFAULT,
                DEFAULT,
                DEFAULT,
                '2020'
              ),
              (
                '96bca832-99b3-4c4d-8913-ab4ca82ec442',
                'Pennsylvania',
                'US',
                'PA',
                's3://global-districtbuilder-dev-us-east-1/regions/US/PA/2020-09-09T19:03:58.174Z/',
                DEFAULT,
                DEFAULT,
                DEFAULT,
                '2010'
              ), (
                '6c440b8d-c26e-4bae-850f-dbff37fe0209',
                'Illinois',
                'US',
                'IL',
                's3://global-districtbuilder-dev-us-east-1/regions/US/IL/2021-06-04T15:05:37.089Z/',
                DEFAULT,
                DEFAULT,
                DEFAULT,
                '2010'
              ), (
                '852fa086-de7c-4edd-b666-004b6ff8dc6c',
                'Delaware',
                'US',
                'DE',
                's3://global-districtbuilder-dev-us-east-1/regions/US/DE/2020-09-09T19:50:10.921Z/',
                '2020-09-09 19:50:10.921',
                TRUE,
                TRUE,
                '2010'
              ), (
                '411c5908-2a83-40e9-863b-303931a1c119',
                'Delaware',
                'US',
                'DE',
                's3://global-districtbuilder-dev-us-east-1/regions/US/DE/2021-06-11T23:03:36.938Z/',
                '2021-06-11 23:03:36.938',
                FALSE,
                FALSE,
                '2020'
             ), (
                '893a9538-3f14-4225-9c91-d54ba818ab0d',
                'New Jersey',
                'US',
                'NJ',
                's3://global-districtbuilder-dev-us-east-1/regions/US/NJ/2021-10-26T01:42:56.227Z/',
                '2021-10-26 01:42:56.227',
                DEFAULT,
                DEFAULT,
                '2020'
             )
              ON CONFLICT DO NOTHING;
            "

        # Add chambers to the database
        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              INSERT INTO chamber
              VALUES (
                'e7f5999f-88d9-4c58-ab85-f65eae843ea1',
                'House of Representatives',
                 18,
                '6c440b8d-c26e-4bae-850f-dbff37fe0209',
                NULL
              ),
              (
                '2202e945-161b-4f84-a282-5d65c7ba16b7',
                'House of Representatives',
                 18,
                '96bca832-99b3-4c4d-8913-ab4ca82ec442',
                NULL
              ),
              (
                'ac0b99f1-baf9-4ee0-9f19-a6228ca61ab3',
                'General Assembly',
                 40,
                '893a9538-3f14-4225-9c91-d54ba818ab0d',
                ARRAY[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
              )
              ON CONFLICT DO NOTHING;
            "

        # Add testing organization
        ./scripts/manage update-organization dev-data/azavea.yaml
        
        # Add user to testing organization
        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              INSERT INTO organization_users_user VALUES((SELECT id FROM organization WHERE slug = 'azavea'), (SELECT id FROM \"user\" ORDER BY id LIMIT 1)) ON CONFLICT DO NOTHING;
            "

        # Set testing organization admin (no-op if there are no users) 
        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              UPDATE organization SET user_id = (SELECT id FROM \"user\" ORDER BY id LIMIT 1) WHERE slug = 'azavea';
            "
    fi
fi
