#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Load region configs and a test organization for development purposes.

This avoids having to process GeoJSON locally and publish it to S3.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Bring up PostgreSQL and NestJS in a way that respects
        # configured service health checks.
        docker-compose \
            -f docker-compose.yml \
            up -d database server

        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              INSERT INTO region_config
              VALUES (
                'e7728e7d-cf2e-45e9-a8d8-e44699d87a21',
                'Michigan',
                'US',
                'MI',
                's3://global-districtbuilder-dev-us-east-1/regions/US/MI/2020-09-08T20:15:12.635Z/',
                DEFAULT,
                DEFAULT
              ), (
                '4a48268f-ddcf-4ae9-b41f-23cda93c3eba',
                'Dane County',
                'US',
                'WI',
                's3://global-districtbuilder-dev-us-east-1/regions/US/WI/2021-02-08T15:19:22.145Z/',
                DEFAULT,
                DEFAULT
              ), (
                '96bca832-99b3-4c4d-8913-ab4ca82ec442',
                'Pennsylvania',
                'US',
                'PA',
                's3://global-districtbuilder-dev-us-east-1/regions/US/PA/2021-02-08T18:07:18.957Z/',
                DEFAULT,
                DEFAULT
             )
              ON CONFLICT DO NOTHING;
            "

        # Add testing organization
        ./scripts/manage update-organization dev-data/azavea.yaml
        
        # Add user to testing organization
        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              INSERT INTO organization_users_user VALUES((SELECT id FROM organization WHERE slug = 'azavea'), (SELECT id FROM \"user\" ORDER BY id LIMIT 1));
            "

        # Set testing organization admin (no-op if there are no users) 
        docker-compose \
            exec database psql -U districtbuilder districtbuilder -c "
              UPDATE organization SET user_id = (SELECT id FROM \"user\" ORDER BY id LIMIT 1) WHERE slug = 'azavea';
            "
    fi
fi
