#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    docker-compose up -d database
    docker-compose run --no-deps --rm manage ./bin/run "$@"
fi
