#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0") [migration_name]
Generates a migration using typeorm.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose \
            run --rm server yarn run migration:generate "$@"
    fi
fi
