#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Bring up all of the services required for the project to function.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    elif [[ "${1}" == "--debug" ]]; then
        docker-compose -f docker-compose.yml -f docker-compose.debug.yml up server client
    else
        docker-compose up server client
    fi
fi
