#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Start backend application services.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose up server client
    fi
fi
