#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run linters and tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Linting server source code"
        docker-compose \
            run --rm --no-deps server \
            yarn lint
        docker-compose \
            run --rm --no-deps server \
            yarn check-format

        echo "Executing server test suite"
        docker-compose \
            run --rm --no-deps server \
            yarn test --watchAll=false

        echo "Linting client source code"
        docker-compose \
            run --rm --no-deps client \
            yarn lint
        docker-compose \
            run --rm --no-deps client \
            yarn check-format

        echo "Executing client test suite"
        docker-compose \
            run --rm --no-deps client \
            yarn test --watchAll=false
    fi
fi
