#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run linters and tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Linting Bash scripts"
        docker-compose \
            -f docker-compose.ci.yml \
            run --rm --no-deps shellcheck \
            scripts/*

        echo "Linting source code"
        ./scripts/npm server run lint

        echo "Checking formatting"
        ./scripts/npm server run format:check

        echo "Executing client test suite"
        ./scripts/npm server run test:client

        echo "Executing server test suite"
        if [[ -n "${CI}" ]]; then
            GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                -f docker-compose.yml \
                -f docker-compose.ci.yml \
                run --rm --no-deps \
                -e "CI=${CI}" \
                server \
                run test:server

            GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                -f docker-compose.yml \
                -f docker-compose.ci.yml \
                run --rm --no-deps \
                -e "CI=${CI}" \
                server \
                run e2e
        else
            ./scripts/npm server run test:server
            ./scripts/npm server run server:e2e
        fi
    fi
fi
