#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Setup external project dependencies.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Updating dependencies"
        yarn install
    fi
fi
