version: "3"
services:
  k6:
    image: loadimpact/k6
    environment:
      - JWT_AUTH_TOKEN
      - HAR_FILE
      - REQ_ORIGIN
    volumes:
      - ./:/scripts
    command: run /scripts/harness.js
